// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5eQ3fH4LJ1OfDeaOm81Rc53x5yquHC0s',
    appId: '1:281754873407:web:1193bc5fd111536139528a',
    messagingSenderId: '281754873407',
    projectId: 'mubielist',
    authDomain: 'mubielist.firebaseapp.com',
    storageBucket: 'mubielist.firebasestorage.app',
    measurementId: 'G-W8WYH50DXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHOi1_giaupEASKRiH9J2vqFOMEO4Rjyw',
    appId: '1:281754873407:android:e9be3b382caf321739528a',
    messagingSenderId: '281754873407',
    projectId: 'mubielist',
    storageBucket: 'mubielist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8QIxgTTKMAPNVuP1dyPNq7eWHSR2a5h4',
    appId: '1:281754873407:ios:9dbe377ed430afd739528a',
    messagingSenderId: '281754873407',
    projectId: 'mubielist',
    storageBucket: 'mubielist.firebasestorage.app',
    iosBundleId: 'com.example.movieApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8QIxgTTKMAPNVuP1dyPNq7eWHSR2a5h4',
    appId: '1:281754873407:ios:9dbe377ed430afd739528a',
    messagingSenderId: '281754873407',
    projectId: 'mubielist',
    storageBucket: 'mubielist.firebasestorage.app',
    iosBundleId: 'com.example.movieApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5eQ3fH4LJ1OfDeaOm81Rc53x5yquHC0s',
    appId: '1:281754873407:web:6bae3ac6308362f639528a',
    messagingSenderId: '281754873407',
    projectId: 'mubielist',
    authDomain: 'mubielist.firebaseapp.com',
    storageBucket: 'mubielist.firebasestorage.app',
    measurementId: 'G-BL4EBNSPY7',
  );
}
